### ISSUE TITLE
Label

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#138]
### Task

Possibly reusing USWDS' https://standards.usa.gov/labels/, extend as/if necessary (e.g. color, size, etc). Also generally known as "Flag" or "Pill".

- [x] Design 
- [x] Build HTML/CSS
- [x] Variations (e.g. small, large, colors, etc)
- [x] ~~`aria`, if at all~~

### Inspiration

Bootstrap:
![image](https://cloud.githubusercontent.com/assets/1165933/19947399/e5160f7e-a115-11e6-942e-3778dc79eab7.png)

**Comment by francisrupert** [comment]
### Draft Status

![image](https://cloud.githubusercontent.com/assets/1165933/20145844/2d02b35e-a667-11e6-8b83-105e8513f0ec.png)

**Comment by francisrupert** [comment]
closed via 	b92df9d
