### ISSUE TITLE
Badge

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#139]
### Task

- [x] Design 
- [x] Build HTML/CSS
- [x] Variations (e.g. small, large, colors, etc)
- [x] ~~`aria`, if at all~~

### Inspiration

![image](https://cloud.githubusercontent.com/assets/1165933/19947456/31602478-a116-11e6-83fa-bf29b3c7f93f.png)

related to labels, #138

**Comment by francisrupert** [comment]
### Draft Status

![image](https://cloud.githubusercontent.com/assets/1165933/20145882/54a41812-a667-11e6-84f4-5e88753b7aa8.png)

**Comment by francisrupert** [comment]
closed via 	b92df9d
