### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#145]
### Task

- [x] Sketch
- [x] Design 
- [x] Build HTML/CSS
  - [x] Variations/Examples (assuming 1 general variation, multiple examples)
  - [x] RWD
- [x] Accessibility features, e.g. in a `<nav>`, screenreader-only text, `aria-current, aria-label`, etc
- [x] Account for button versions, i.e. in SPA they could be `<button>` instead of `<a>`
- [x] Test test test

#### On page 1 of 3

Prev&nbsp;&nbsp;&nbsp;&nbsp;**1**&nbsp;&nbsp;[2](#page)&nbsp;&nbsp;[3](#page)&nbsp;&nbsp;&nbsp;&nbsp;[Next](#page)

#### On page 2 of 3

[Prev](#page)&nbsp;&nbsp;&nbsp;&nbsp;[1](#page)&nbsp;&nbsp;**2**&nbsp;&nbsp;[3](#page)&nbsp;&nbsp;&nbsp;&nbsp;[Next](#page)

#### On page 56 of 120

[Prev](#page)&nbsp;&nbsp;&nbsp;&nbsp;[1](#page)&nbsp;&nbsp;...&nbsp;&nbsp;[55](#page)&nbsp;&nbsp;**56**&nbsp;&nbsp;[57](#page)&nbsp;&nbsp;...&nbsp;&nbsp;[120](#page)&nbsp;&nbsp;&nbsp;&nbsp;[Next](#page)

**Comment by francisrupert** [comment]
Aiming for [2.1.5 Milestone](https://github.com/USDA-FSA/fsa-style/milestone/16) now.

**Comment by francisrupert** [comment]
![image](https://user-images.githubusercontent.com/1165933/41538927-07afcf18-72d2-11e8-8eae-c9ada976be2a.png)

**Comment by francisrupert** [comment]
### Status 

Generally done. Stress-testing, browser-testing, scalable-testing, etc. 

### Screenshots of current state

<S | S+ | M+
------------ | ------------- | -------------
![image](https://user-images.githubusercontent.com/1165933/41663334-ccc9488c-7468-11e8-959f-cca64d955c5d.png) | ![image](https://user-images.githubusercontent.com/1165933/41663349-d95dec88-7468-11e8-96e6-c588ac74ace5.png) | ![image](https://user-images.githubusercontent.com/1165933/41663368-e60e9554-7468-11e8-8aae-2059e470c7a6.png)

**Comment by francisrupert** [comment]
### IE CSS bugs:

- [ ] **1**. Something about the styles introduced at `breakpoint(M)` borks out on me:

S | M+
------------ | -------------
![image](https://user-images.githubusercontent.com/1165933/41850860-b6e5f452-784b-11e8-96e9-d1df53071b96.png) | ![image](https://user-images.githubusercontent.com/1165933/41850876-c430fb52-784b-11e8-9c91-b6abb51df2f4.png)

- [ ] **2**. Disabled _Previous/Next_ not rendering in IE

Correct | IE
-- | --
![image](https://user-images.githubusercontent.com/1165933/41850959-021af4e0-784c-11e8-83c6-fc4f6e78dc3c.png) | ![image](https://user-images.githubusercontent.com/1165933/41851093-73e919f8-784c-11e8-8c00-5291df3b3582.png)
