### ISSUE TITLE
Search field

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#152]
### Task

- [x] Design 
- [x] Build HTML/CSS
- [x] Variations (default, large, small)
- [x] Integrated in Nav Global

### Inspiration

Possibly reuse or _modify_ [USWDS' equivalent](https://standards.usa.gov/search-bar/)

![image](https://cloud.githubusercontent.com/assets/1165933/20577750/6170a7fe-b189-11e6-8eb7-ef72d4f69f0a.png)

**Comment by francisrupert** [comment]
![image](https://user-images.githubusercontent.com/1165933/48844489-9a3a7b00-ed5f-11e8-80a7-c6a56db1548c.png)
