### ISSUE TITLE
Component: Switch 

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#153]
### Task

- [x] Research, [particularly for Accessibility concerns](https://scottaohara.github.io/a11y_styled_form_controls/#switches--toggle-buttons) (iow, don't take this component lightly)
- [x] Prototype
- [x] Design 
- [x] Build for Production
   - [x] Variations / States
- [x] JavaScript Demo (non-production, prototype-quality)

### HTML General Idea

```html
<span class="fsa-switch">
  <input class="fsa-switch__el" type="checkbox" id="UNIQUE-ID-1234">
  <label class="fsa-switch__label" data-on="Yup" data-off="Nope" for="UNIQUE-ID-1234">Switch Label</label>
</span>
```

#### Considerations
1. Form opinion on how this component **functionally** differs from a `<input type="checkbox">`. i.e. Switch is for _instataneous_ toggling without form submission, it takes immediate affect. A checked `<input type="checkbox">` only takes once its associated form is submitted.
1. The "value", e.g. "on" or "off"; "yes" or "no" is passed via CSS from the `data-` attributes. For this to work, those values must be fewer than 3 or 4 characters. 
   * Maybe there's a variation with no visible text value, [like iOS](https://user-images.githubusercontent.com/1165933/36209239-d78c7426-1160-11e8-9d33-30cc409c5270.png) or [Android / Material](https://user-images.githubusercontent.com/1165933/36209451-5fcaf9c0-1161-11e8-863a-8a30c835d1f1.png).
 1. While this approach requires location of `<label>` to be immediately adjacent to the `<input>`, a `<label>` with no visible text may be a variation. 
    * Subsequently, a corresponding `<label>` with same targeted `for` value can still exist elsewhere. Rare use case, but need to account for it.

### Inspiration

![image](https://user-images.githubusercontent.com/1165933/66916757-8637e180-efe1-11e9-850a-14a36e378000.png)

**[USPTO](http://uspto.github.io/designpatterns/1.x/docs/components/formControls.html#toggle-switches)**
![image](https://cloud.githubusercontent.com/assets/1165933/20802511/e2665ca4-b7b1-11e6-80bb-ae0ddc9af824.png)
