### ISSUE TITLE
Growl

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#177]
### Task

- [x] Design 
- [x] Build HTML/CSS
- [x] Variations
- [x] Port from PCP
- [x] Script demo of states/interaction/etc (plain vanilla, non-jQuery)
- [x] Focus transfer
- [x] Keyboard trapping

### Etc.

Port in from PCP, and adjust as needed.

![image](https://user-images.githubusercontent.com/1165933/29780643-226e936c-8bdc-11e7-8f59-816134deedf9.png)

**Comment by francisrupert** [comment]
@bignamehere,

Assigned. Same vanilla JS scripting idea mentioned in https://github.com/USDA-FSA/fsa-style/issues/178#issuecomment-330959548

**Comment by bignamehere** [comment]
@francisrupert 

ready for Peer review. Code can be [reviewed here](https://github.com/USDA-FSA/fsa-style/commit/f9c777bca8966562a9ecc68367b68ad1f284a062) and you can ignore that first commented out buttons as I have [cleaned them up here](https://github.com/USDA-FSA/fsa-style/commit/4375da3c33841a716083eddfeb58071ef89351a9).

**Comment by bignamehere** [comment]
@francisrupert 

forgot to mention that I didn't include any tabbing or key trapping, because I wanted to discuss how this should be handled as an alert (growl) can be seen as augmentation as opposed to necessary or functionality.

If tabbing were to be included, I don't believe trapping should be used, because the interface is not restricted. Thoughts?

**Comment by francisrupert** [comment]
I forgot to mention focus and keyboard trapping for one of the variations. Indeed the Doc page of Modal omitted that variation, which is a Modal-like but still a Growl variation.

Click the **Reset** button on the Sharepoint-hosted [PCP prototype](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/LOB%20-%20Commodity%20Ops/PCP%20II%20Project/UX/Design/prototypes/master/workflow_mapping.html)

I didn't implement focus transfer and keyboard trapping in my js, but same exact idea.

**Comment by francisrupert** [comment]
@bignamehere,

Looking good, great start. I've structured some feedback below. You might also consider my response as possibly applying to Modal, #178. If you agree, keep #178 open and comment on it with updates to be made.

### Variable Name Collision?

You're using `var triggers, closeButtons` for both **Growl** and **Modal** component, should they be namespaced more safely?

https://github.com/USDA-FSA/fsa-style/blob/be2ba0b0d9cce75f8817ed1b96a0eabd7b0976cc/src/js/components/fsa-growl.js#L12-L13
https://github.com/USDA-FSA/fsa-style/blob/be2ba0b0d9cce75f8817ed1b96a0eabd7b0976cc/src/js/components/fsa-modal.js#L14-L15

### One `fsa-growl-container`

Multiple Growl alerts can occur, effectively stacking within the container. [View this screencast](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/XCut%20-%20UX/1.%20Strategy%20and%20Design%20Guide%20-%20FSA%20and%20USDA/screencasts/growl.webm) for demo.

**The exception:** the modal-like `.pcp-growl-container--centered` variation, [seen in play in PCP](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/LOB%20-%20Commodity%20Ops/PCP%20II%20Project/UX/Design/prototypes/master/workflow_mapping.html), click "Reset".

To repeat my previous comment, that one shall be keyboard-trapped and focused to.

### data-target

Swap out `data-target` in favor of `aria-controls`.
* I'm going to start to employ this elsewhere going forward.
* Assuming success, retroactively apply this to **Modal**

### aria-expanded

The *controlling* button starts as...
```html
<el data-behavior="growl-show" aria-controls="asdf" aria-expanded="false" >...
```
...and is...
```html
<el data-behavior="growl-show" aria-controls="asdf" aria-expanded="true" >...
```
...if its controlled target is `aria-hidden="false"`.

### Swapping out `--hidden` for aria

I'm pretty sure you can change `&--hidden { .... }` to `&[aria-hidden="true"] { .... }` in `_fsa.growl.scss`

And reconcile the same in...

https://github.com/USDA-FSA/fsa-style/blob/be2ba0b0d9cce75f8817ed1b96a0eabd7b0976cc/src/js/components/fsa-growl.js#L44-L62

**Comment by bignamehere** [comment]
@francisrupert 

Updated the Growl with above fixes. Ready for review.

Diff: [8141e00](https://github.com/USDA-FSA/fsa-style/commit/8141e00a2ac8415dedbf72c705bd4d3efc274d06)

**Comment by francisrupert** [comment]
@bignamehere, Growl is looking good. A few notes below:

***

Add...

```scss
&:focus {
  outline: 0;
}
```

...to `.fsa-growl`

***

`.fsa-growl--dismissing` must be initially **added** before it can be removed. And the timing of when to toggle `aria-hidden` occurs afterward.

https://github.com/USDA-FSA/fsa-style/blob/8141e00a2ac8415dedbf72c705bd4d3efc274d06/src/js/components/fsa-growl.js#L73-L89

...updates to something like...

```javascript
function dismissGrowl(g){

  var _growl = g;
  _growl.classList.add('fsa-growl--dismissing');

  setTimeout(function() {
    _growl.className = _growl.className.replace(' fsa-growl--dismissing','');
    _growl.setAttribute('aria-hidden', 'true');

    var _origin = document.querySelector('[data-growl-origin]');
    _origin.removeAttribute('data-growl-origin');
    _origin.setAttribute('aria-expanded', 'false');
    // set focus back to the originating element
    _origin.focus();

  }, 250);

}
```

***

I'd also like to see if we can replace `setTimeout()` with `animationend`. That is, listening for when the `_growl`'s _dismissing_ animation is complete. So something like...

```javascript
function dismissGrowl(g){

  var _growl = g;
  _growl.classList.add('fsa-growl--dismissing');

  _growl.on('webkitAnimationEnd oanimationend msAnimationEnd animationend', function(e) {
    // do the stuff you currently setTimeout()
  });

}
```

That's using jQuery, so that'll need to be vanilla-ized. Several years ago I used http://callmenick.com/post/listen-for-css-animation-events-with-javascript. There may be something better out now, but this one is at least prefixed.

That one generally results in...

```javascript
prefixedEventListener(_growl, 'AnimationEnd', function(e){
  // do the stuff you currently setTimeout()
});
```

**Comment by bignamehere** [comment]
@francisrupert 

I made the updates and pushed to [this branch: c8aa297](https://github.com/USDA-FSA/fsa-style/commit/c8aa297d434a32376343c99b3952d8f29a06a62f).  Shall I merge to develop?

**Comment by bignamehere** [comment]
@francisrupert 

take a look at the fixes. I can't replicate the issues we observed, so hopefully we are good to go.

Diff: [231852e](https://github.com/USDA-FSA/fsa-style/commit/231852ed06a761543c3d0a3e97102b16a66fb0cf)

**Comment by francisrupert** [comment]
Yup, works perfectly. I haven't been able to reproduce it now across Chrome and Firefox on both Windows and Mac.

**One last addition** (promise)

If there are more Growls than window height allows, they are cut off and can't be scrolled to.

**Solution:**

Add the following rules to `.fsa-growl-container`:

```scss
bottom: $size-default;
overflow: auto;
```
Verify that works and **merge to `develop`**.

**Comment by francisrupert** [comment]
:stop_sign: Whoop, belay that order. Adding that `bottom` property means the content below won't be clickable, even when there are no viewable Growls.

If you have another CSS solution, go for it. I'll think on it too.

![image](https://user-images.githubusercontent.com/1165933/31787683-1ff8c944-b4d2-11e7-8169-9530080eb13a.png)

**Comment by francisrupert** [comment]
@bignamehere,

**Update** to [my previous comment](https://github.com/USDA-FSA/fsa-style/issues/177#issuecomment-337997802), do this instead:

```scss
.fsa-growl-container {

  // (....other rules....)

  max-height: calc(100vh - #{$size-default}); // 100% of viewport height minus $size-default (1.2rem)
  overflow-x: hidden;
  overflow-y: auto;

  // (....other rules....)

}
```

**Comment by bignamehere** [comment]
@francisrupert 

made the code fix. I think the solution is good given it being an edge case.

Merge to Develop?

**Comment by francisrupert** [comment]
Awesome, merge away

**Comment by bignamehere** [comment]
merged into develop
