### ISSUE TITLE
Select Multi

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#179]
### Task

- [x] Design 
- [x] Build HTML/CSS (done in PCP)
- [x] Port to `fsa-style`, namespace, any adjustments, etc.
- [x] Variations? 
- [x] Examples; e.g. without "Select all", what else?
- [x] States: at least `disabled`, what else?
- [x] Script demo (plain vanilla, non-jQuery)
  - [x] Select / Deselect all
  - [x] Indeterminate.
    * If at least 2 `.pcp-select-multi__check` are checked, the "Select all" checkbox is indeterminate. [DS Reference](http://usda-fsa.github.io/fsa-design-system/components/checkbox/#indeterminate).
    * Clicking checkbox in indeterminate state **unchecks all**.

**PCP Prototype:** [https://sharepoint....component_select-multi.html](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/LOB%20-%20Commodity%20Ops/PCP%20II%20Project/UX/Design/prototypes/master/component_select-multi.html)

![image](https://user-images.githubusercontent.com/1165933/31250352-2b5f5aac-a9e0-11e7-8473-04728618acaa.png)

**Comment by bignamehere** [comment]
@francisrupert 

Created a branch for Select Multi and added functionality for select all and disabled variations.

commits [e2afbf5](https://github.com/USDA-FSA/fsa-style/commit/e2afbf504e374fadf103744edcf359dab9261095) and [db9d767](https://github.com/USDA-FSA/fsa-style/commit/db9d767704acc556b298337655cdc7d873ce7ece) are ready for peer review.

**Comment by francisrupert** [comment]
@bignamehere,

**Action** 
Pull before you next work on `feature/select-multi` branch to avoid conflict mayhem. 

**Background**
As part of adjusting disabled form elements (#189), I had to account for this component's disabled equivalent too. It was easier to do so by merging my working branch to `feature/select-multi` and adjusting.

I'm completely out of this branch now. So once you've completed the `indeterminate` feature, we'll likely move to `develop` right quick.

**Comment by bignamehere** [comment]
@francisrupert 

I need a second set of eyes on this issue. I have tried a number of ways to try and replicate [the jQuery example](https://css-tricks.com/indeterminate-checkboxes/), but am having issues traversing back up the ancestry nodes to turn indeterminate to checked. I have committed [my code here](https://github.com/USDA-FSA/fsa-style/commit/c3e7c271dbc52765b33cd269560e7747efa9526e). 

Can you take a look and see if you can spot what I am missing.

FYI:
- I have turned off the Select All capabilities because they will need to be rewritten with this new logic.

- I have added a --tiered class that gives more max-height for nested input trees. Needs CSS help later.

**Comment by francisrupert** [comment]
@bignamehere,

While the multi-tiered nested example you're attempting will be a good use case to make available at some point, don't kill yourself to get that working for now. Concentrate on the flat use case.

Solidify the below use case, and then create a **new issue** (referencing this issue) that addresses a multi-tiered example set for a future milestone.

**Nothing is selected**

```
[ ] Select all
[ ] Apple Pie
[ ] Cherry Pie
[ ] Peach Pie
```

**Checking "Cherry Pie" results in indeterminate "Select all"...**

```
[-] Select all
[ ] Apple Pie
[x] Cherry Pie
[ ] Peach Pie
```

**Checking "Select all" when in indeterminate state will *uncheck* all**

```
[ ] Select all
[ ] Apple Pie
[ ] Cherry Pie
[ ] Peach Pie
```

**Checking "Select all" when *none* are checked**

```
[x] Select all
[x] Apple Pie
[x] Cherry Pie
[x] Peach Pie
```

**Unchecking "Cherry Pie" when *all* are checked results in *indeterminate* "Select all"**

```
[-] Select all
[x] Apple Pie
[ ] Cherry Pie
[x] Peach Pie
```

**Comment by bignamehere** [comment]
@francisrupert 

I rebuilt the code for the Select Multi with the Select All feature. Based on my research of various examples online, I believe we should not have the Select All checkbox uncheck all when in the Indeterminate state. There are a few UX and technical reasons as well, including that being counter intuitive to the label "Select All". Gmail is the only example I saw that used this behavior, but their pattern does not include any labels at all. To be honest, the Gmail implementation seems rather confusing.

Let's discuss further when you have some time.

**Comment by bignamehere** [comment]
@francisrupert 

For reference, here are the examples I looked at:

[Example One](https://css-tricks.com/indeterminate-checkboxes/)

[Example One Code Pen](https://codepen.io/anon/pen/ZaYRgg?editors=0010)

[Example Two](http://jsfiddle.net/VMwareDesign/DHXy4/)

[Example](https://github.com/sevar83/indeterminate-checkbox) that talks about behavior of indeterminate state.

[Example five](https://codepen.io/VMwareDesign/pen/eJyXEE)

**Comment by bignamehere** [comment]
closing as per [705e9ce](https://github.com/USDA-FSA/fsa-style/commit/705e9ceb2489ab25a2b0e259631fa2dd4752968d)

**Comment by bignamehere** [comment]
Reopening. Noticed a bug in IE.
