### ISSUE TITLE
Spinbox

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#180]
## Task

- [x] Design 
- [x] Build HTML/CSS
- [x] Vanilla JS - this one is less straight-forward than Modal and Growl. 
- [x] Variations / States / Examples

### Etc.

Port in from PCP, and adjust as needed.
[https://sharepoint.fsa.usda.net....component_spinbox.html](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/LOB%20-%20Commodity%20Ops/PCP%20II%20Project/UX/Design/prototypes/master/component_spinbox.html)

![image](https://user-images.githubusercontent.com/1165933/29780704-550b501c-8bdc-11e7-8416-c99f0d612468.png)

**Comment by francisrupert** [comment]
Aiming for 2.1.5

**Comment by francisrupert** [comment]
@bignamehere,

**Review Request**: I've ported in the Spinbox from PCP, including rewriting the jQuery-based script to Vanilla JS - following the approach you've done for previous components. Viewable at
[Sharepoint .... XCut - UX ... FSA Design System - Prototyping/feature/port-pcp-spinbox/](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/XCut%20-%20UX/1.%20Strategy%20and%20Design%20Guide%20-%20FSA%20and%20USDA/FSA%20Design%20System%20-%20Prototyping/feature/port-pcp-spinbox/index.html#component__spinbox)

Can you provide feedback on [`src/js/components/fsa-spinbox.js`](https://github.com/USDA-FSA/fsa-style/blob/feature/port-pcp-spinbox/src/js/components/fsa-spinbox.js) in addition to its design (straight rip from PCP)?

For jQuery-to-Vanilla comparison purposes, you can view PCP's at [`pcp/master/src/js/prototype.js#L562-L581`](https://github.com/USDA-FSA/pcp/blob/master/src/js/prototype.js#L562-L581)

![image](https://user-images.githubusercontent.com/1165933/41994289-9426fdf2-7a13-11e8-9165-3502904e9133.png)

**Comment by bignamehere** [comment]
@francisrupert  I moved the two utility methods related to browser version, etc to the Helper.js utilities library. I reviewed the rest of the code, and it doesn't look like it does much by output alerts, which would not really need to be updated or optimized.

**Comment by francisrupert** [comment]
Closed via f7824d614f1dc6129a394983e8906386bc7142da, c8621f6d06ede777613fdfff9548edaa7b57c6db, c36d69eb0a211b96eba5197f2b2f2fb3d27834d2, b01fd3575e032cf38b7f1593dcf4c13da7859a1f, 4e17ee407aa43be6fcaa0b35a099098056a287d8, b8f84cbee544f61d00c68c02e52b7f5d823569e2
