### ISSUE TITLE
Global Nav

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#182]
### Task

- [x] Design 
- [x] Build HTML/CSS
- [x] Variations
- [x] Prototype scripting (not meant to be Production-quality)
- [x] Responsive? (Likely nice-to-have for MVP)

### Etc.

Refer to DUT prototype as starting point. Use initial style from PCP.

![image](https://user-images.githubusercontent.com/1165933/29825964-9dc2507a-8c9b-11e7-8fd2-3cc6f4c124c2.png)

**Comment by francisrupert** [comment]
closed via 67e07d2
