### ISSUE TITLE
RWD Viewer

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#272]
### Task

Simple, low-key, minimal-JS resizing of an `iframe` to demonstrate responsive views of select components. 

- [x] Design 
- [x] Build HTML/CSS/JS
- [x] Refactor `iframe`s
- [x] Apply to
  - [x] Grid System
  - [x] Margins
  - [x] Padding
  - [x] Float
  - [x] Text Size
  - [x] Text Alignment
  - [x] Text Headers
  - [x] Visibility
  - [x] Header: Top Hat
  - [x] Header: App
  - [x] Header: Nav Global
  - [x] Footer: Global Footer
  - [x] Pagination
  - [x] Responsive Tables
  - [x] Stepped Control
  - [x] Content Tabs
  - [x] Modal

### Initial protoyped idea:

![image](https://user-images.githubusercontent.com/1165933/49105293-d5e4b180-f245-11e8-9ee9-3a9058d55328.png)
