### ISSUE TITLE
Select Element

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#28]
### Initial set

* [x] default
* [x] block
* [x] focus
* [x] disabled
* [x] ~~hover~~
* [x] multiple; that is, style should support it but don't surface in visual index it since we'd rather them use checkboxes to select multiple. Background: it's confusing to users at best; at worst, the form is useless for users that don't grok its functionality (i.e., `ctrl`, `cmd`, or `shift` click). Design System will discourage its use and provide alternatives.

### Variations

* Error, etc. Covered by #29
* [x] big (synced with equivalent in #27 and #22)
* [x] small (synced with equivalent in #27 and #22)
* others TBD (possibly deferred indefinitely until project need arises)
* custom variations (e.g., [Chosen](https://harvesthq.github.io/chosen/) may be possibly deferred indefinitely until project need arises)?

## Other requirement

* [x] Coordinate sizing with buttons, #22, and #27 i.e. height in sync
