### ISSUE TITLE
Stronger :focus treatment

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#294]
### Task
Adopt stronger `:focus` treatment seen on USWDS. (This is not a duplicate of #290)

#### Finding and exceptions

Most focusable elements have been found to work perfectly with the generic, global focus treatment (color, border, and offset); however, some require one-off minor adjustments (e.g. adjust offset). In order of priority:

- [x] (Global)
- [x] Checkbox
- [x] Radio
- [x] Buttons
- [x] Stepped Tabs
- [x] Content Tabs
- [x] Button Group
- [x] Spinbox
- [x] Label (`<a>` vs `<button>`)
- [x] Badge  (`<a>` vs `<button>`)
- [x] Global Nav
- [x] Table Sort
- [x] Docs anchor (`.docs__anchor`)
- [x] Docs nav (`.docs__primary-nav-sub-link`)
- [x] Skip nav

### Presumptive Solution

Start with the assumption the following series of selectors is the appropriate starting point (more than merely `:focus {}`), and then one-off-adjust each element and component carefully.

```scss
[contentEditable=true]:focus,
[href]:focus,
[tabindex]:focus,
button:not([disabled]):focus,
iframe:focus,
input:not([disabled]):focus,
select:not([disabled]):focus,
textarea:not([disabled]):focus {
  (props)
}
```

**Comment by francisrupert** [comment]
(Edited initial post with findings and more specific details).
