### ISSUE TITLE
Design and Build: Progress Component

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#356]
### Sub-tasks

- [x] Research
- [x] Prototype
- [x] Design
- [x] Build for Production
   - [x] Screenreader implications 
   - [x] Variations / States (e.g. `indeterminate`)
- [x] JavaScript Demo (non-production, prototype-quality)

### Summary

If browser support and **screenreader** support for `<progress>` isn't enough to use as is, this task aims to _mostly_ emulating the native `<progress>` element while developing opinion on appropriate level of support to design and build this component. For example, while not _fully_ emulating accessibility support, it likely could be a good example of Progressive Enhancement.

### Initial Prototype
https://codepen.io/francisrupert/pen/QWLyRZx?editors=1000

### Background
Was initiated in SPA Reference App ([ASC-186](https://issues.tools.fsa.usda.gov/browse/ASC-186), [ASC-222](https://issues.tools.fsa.usda.gov/browse/ASC-222)). Intended to outright replace the "Circular Loading" (#355, [ASC-215](https://issues.tools.fsa.usda.gov/browse/ASC-215)) component and extend.

### Related
Similar to the `<meter>` element (#361) in appearance, its role is distinct and thus its own component. Design System documentation shall aid to distinguish usage..

**Comment by francisrupert** [comment]
Re-opening to address screenreader compatibility. Current markup and aria usage is iffy on how its content gets announced consistently.
