### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#36]
## Task

Establish generic grid approach.

* Float vs Inline-Blocks vs Flex?
* Francis home-rolls one as he's done many times, or adopt USWDS' Neat-based one, or...?
* While a generic grid should be available, surface options to create *semantic*-based grid layouts.   
  * Preliminary thinking: this amounts to summarizing USWDS' use of Neat (i.e. `@include span-columns(4)`) and deferring to their [Docs](http://thoughtbot.github.io/neat-docs/latest/) on using.

### General Requirements

- [x] Responsive Options, how many name-spaced breakpoints, e.g. `g-ml--1-4` for "25% width at ML breakpoint"
- [x] Surface mixins. Could very well be simple example and then point to Neat Docs.
- [x]  With *and* without gutters
