### ISSUE TITLE
Google Analytics - Component Behavior Tracking

### ISSUE THREAD

**Issue by bignamehere** [USDA-FSA/fsa-style#462]
Add GA Tracking functionality to the following on page components:

- [x] Select Multi
- [x] Date Picker
- global nav (NOTHING TO TRACK)
- [x] Stepped Controls - Modals
- [x] Progress
- [x] Slider
- [x] Growl
- [x] Modal
- [x] Sticky Header - Hide Nav bar button
- [x] External Links to FPAC resources
- [x] On-page Anchor links

**Comment by bignamehere** [comment]
closing and if more tracking is needed for other pages or section, a new Issue will be created.
