### ISSUE TITLE
CSS Utilities: border

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#468]
Spun off from #381

### Utilities
- [x] Border
  - [x] Border Width
    - [x] rwd
  - [x] Border Color
    - [x] rwd
  - [x] Border Radius
    - [x] rwd
- [x] Border Between (Lobotomized Owl)
  - [x] Border Between Width
    - [x] vertical
    - [x] horizontal
    - [x] rwd
  - [x] Border Between Color
    - [x] rwd

### Task

- [x] Research
- [x] Design 
- [x] Prototype
  - [x] [Prototype Server](https://usdagcc.sharepoint.com/sites/FBC-UX/XCut/1.%20FPAC%20Design%20System/Prototyping/2.6.0/index.aspx) 
  - [x] Base
  - [x] Responsive Scopes
  - [x] Stress test
  - [x] Accessibility
- [ ] Build for Production
   - [x] Variations / States (possibly examples)
   - [x] Test in real-world implementions
   - [x] Kitchen Sink
