### ISSUE TITLE
Icon set: Build

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#469]
### What

Via #49, the Icon Set has been chosen and approved. 

### Task

- [x] Research
- [x] Design 
- [x] Prototype
  - [x] Base
  - [x] Responsive Scopes (i.e. `fsa-level@m`)
  - [x] Stress test
  - [x] Accessibility
  - [x] [Prototype Server](https://usdagcc.sharepoint.com/sites/FBC-UX/XCut/1.%20FPAC%20Design%20System/Prototyping/2.6.0/index.aspx) 
- [ ] Build for Production
   - [x] Variations / States
   - [x] Examples
   - [x] Test in real-world implementions
   - [x] Kitchen Sink
     - [x] Identify "Most Common" starting grid of icons (comprehensive keyword-based search will be on [DS site](https://usda-fsa.github.io/fsa-design-system/components/icons/))
   - [x] Add examples to other Components, e.g [samples prototyped](https://usdagcc.sharepoint.com/sites/FBC-UX/XCut/1.%20FPAC%20Design%20System/Prototyping/2.6.0/index.aspx). 
   - [ ] [Prototype Server](https://usdagcc.sharepoint.com/sites/FBC-UX/XCut/1.%20FPAC%20Design%20System/Prototyping/2.6.0/index.aspx)
