### ISSUE TITLE
Color: create FSA-specific palette

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#6]
The [USDWS color palette](https://standards.usa.gov/visual-style/#palette) provides a robust foundation for FSA to make design decisions on which colors to use, ignore, extend, modify, and/or re-categorize. For example, while the USWDS "primary" color is blue, the FSA primary color is green.

### General SASS Strategy

1. Import USWDS `src/stylesheets/core/_defaults.scss`
2. Override and extend in `src/stylesheets/core/_variables--fsa.scss`

### Tasks

- [x] **Naming convention** (e.g., -light, -lighter, -lightest vs -100, -200, -300)
- [x] **Core Palette** (e.g., "Primary, Secondary, Tertiary")
- [x] **Accents**
- [x] **Tints and Shades**
- [x] **Specialty** (e.g., single-purpose use)

**Comment by francisrupert** [comment]
General commit activity:

* 8ffd9d7b01a4d8e78415f1a9489093adf5a02cb5
* 14008b8099a29c1e55c28bf1c12fff4c8a3560fc
* 4ed0b80c5c2e4312efc74ea14ccf863d1ed36423
* 3377a6f94824658c608b0ff23d04afdffa80fc66
* 12796def2c93edb55cb448808952f58b60d82d34
* 4299f27b568c892935d4799a34427f6d6b3f192c
* 693ce10e6752c02fec260e83b206c78fc9fe018a
* 232a458a7f1483b587c6f0a45cf2a0900ec7f92e
* d96e4494aa82a06b78cdfc0e50503cfbf44eb8a5

**Comment by brianmillsUX** [comment]
Minor edits made to enhance grammar and clarity; in-line with team discussion and great start!
